# Enable CSRF protection for forms and logins/logouts
framework:
    form:
        csrf_protection:
            token_id: submit

    csrf_protection:
        # Remove stateless tokens for better HTTPS compatibility
        # stateless_token_ids:
        #     - submit
        #     - authenticate
        #     - logout
