index:
    path: /
    controller: App\Controller\HomeController::index

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    methods: GET

# Public checklist routes
checklist_show:
    path: /checklist/{id}
    controller: App\Controller\ChecklistController::show
    requirements:
        id: '\d+'

checklist_submit:
    path: /checklist/{id}/submit
    controller: App\Controller\ChecklistController::submit
    methods: [POST]
    requirements:
        id: '\d+'

# Public checklist form with parameters
checklist_form:
    path: /form
    controller: App\Controller\ChecklistController::form

# Admin routes
admin_dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index

admin_checklists:
    path: /admin/checklists
    controller: App\Controller\Admin\ChecklistController::index

admin_checklist_new:
    path: /admin/checklists/new
    controller: App\Controller\Admin\ChecklistController::new

admin_checklist_edit:
    path: /admin/checklists/{id}/edit
    controller: App\Controller\Admin\ChecklistController::edit
    requirements:
        id: '\d+'

admin_checklist_delete:
    path: /admin/checklists/{id}/delete
    controller: App\Controller\Admin\ChecklistController::delete
    methods: [POST]
    requirements:
        id: '\d+'

admin_submissions:
    path: /admin/submissions
    controller: App\Controller\Admin\SubmissionController::index

admin_submissions_checklist:
    path: /admin/submissions/{checklistId}
    controller: App\Controller\Admin\SubmissionController::byChecklist
    requirements:
        checklistId: '\d+'

# Gruppen-Verwaltung
admin_group_create:
    path: /admin/checklists/{id}/groups/new
    controller: App\Controller\Admin\GroupController::create
    requirements:
        id: '\d+'

admin_group_edit:
    path: /admin/groups/{id}/edit
    controller: App\Controller\Admin\GroupController::edit
    requirements:
        id: '\d+'

admin_group_delete:
    path: /admin/groups/{id}/delete
    controller: App\Controller\Admin\GroupController::delete
    methods: [POST]
    requirements:
        id: '\d+'

# Gruppen-Elemente Verwaltung
admin_group_item_add:
    path: /admin/groups/{id}/items/new
    controller: App\Controller\Admin\GroupController::addItem
    requirements:
        id: '\d+'

admin_group_item_edit:
    path: /admin/items/{id}/edit
    controller: App\Controller\Admin\GroupController::editItem
    requirements:
        id: '\d+'

admin_group_item_delete:
    path: /admin/items/{id}/delete
    controller: App\Controller\Admin\GroupController::deleteItem
    methods: [POST]
    requirements:
        id: '\d+'

# E-Mail-Template Verwaltung
admin_checklist_email_template:
    path: /admin/checklists/{id}/email-template
    controller: App\Controller\Admin\ChecklistController::emailTemplate
    requirements:
        id: '\d+'

admin_checklist_email_template_download:
    path: /admin/checklists/{id}/email-template/download
    controller: App\Controller\Admin\ChecklistController::downloadEmailTemplate
    requirements:
        id: '\d+'

admin_checklist_email_template_reset:
    path: /admin/checklists/{id}/email-template/reset
    controller: App\Controller\Admin\ChecklistController::resetEmailTemplate
    methods: [POST]
    requirements:
        id: '\d+'
